---
- hosts: localhost
  gather_facts: no
  vars:
    config: "oneview_config.json"
    server_profile_template: "SPT-ESXi"
    server_profile_name: "nathan-test-8"
    os_deployment_plan: "ESXi-6.7_DP"
    ip_address: "10.188.0.115"
    domainName: "synergy.local"
    dns1: "10.188.0.2"
    dns2: "10.188.0.3"
    gateway: "10.188.0.1"
    netmask: "255.255.255.0"
    hostname: "test-node-1"
    connectionid: 1
    serverhardware: "MXQ71906M7, bay 6"
    esxi_password: "Password123"
    vcenter_hostname: ""
    vcenter_username: ""
    vcenter_password: ""
  tasks:
  - name: Read the environment variables
    set_fact:
      ov_hostname: "{{ lookup('env', 'ONEVIEWSDK_IP') }}"
      ov_username: "{{ lookup('env', 'ONEVIEWSDK_USERNAME') }}"
      ov_password: "{{ lookup('env', 'ONEVIEWSDK_PASSWORD') }}"
      ov_api_version: "{{ lookup('env', 'ONEVIEWSDK_API_VERSION') }}"
  - name: Get network URL from connection ID
    oneview_network_set_facts:
      hostname: "{{ ov_hostname }}"
      username: "{{ ov_username }}"
      password: "{{ ov_password }}"
      api_version: "{{ ov_api_version}}"
      name: 'vcf-networkset'
    delegate_to: localhost
    register: network_sets
  - name: Create server from server profile template with OS deployment for ESXi
    oneview_server_profile:
      hostname: "{{ ov_hostname }}"
      username: "{{ ov_username }}"
      password: "{{ ov_password }}"
      api_version: "{{ ov_api_version}}"
      data:
        name: "{{ server_profile_name }}"
        serverProfileTemplateName: "{{ server_profile_template }}"
        serverHardwareName: "{{ serverhardware }}"
        osDeploymentSettings:
          osDeploymentPlanName: "{{ os_deployment_plan }}"
          osCustomAttributes:
            - name: Hostname
              value: "{{ hostname }}"
            - name: DomainName
              value: "{{domainName}}"
            - name: ManagementNIC.connectionid
              value: "{{ connectionid }}"
            - name: ManagementNIC.NetworkUri
              value: "{{ network_sets['ansible_facts']['network_sets'][0]['networkUris'][connectionid] }}"
            - name: SSH
              value: enabled
            - name: Password
              value: "{{ esxi_password }}"
            - name: ManagementNIC.dns1
              value: "{{ dns1 }}"
            - name: ManagementNIC.dns2
              value: "{{ dns2 }}"
            - name: ManagementNIC.gateway
              value: "{{ gateway }}"
            - name: ManagementNIC.ipaddress
              value: "{{ ip_address}}"  
            - name: ManagementNIC.dhcp
              value: false
            - name: ManagementNIC.netmask
              value: "{{ netmask }}"
            - name: ManagementNIC.constraint
              value: userspecified
            - name: ManagementNIC.ipv4disable
              value: false
            - name: ManagementNIC.vlanid
              value: 0
      params: # Supported only in API version >= 600
        force: True
    delegate_to: localhost